import { describe, expect, it } from "vitest";
import { buildChatGPTBundle, buildExpensesCsv, buildFullBackup, buildItemsCsv, EXPORT_VERSION, exportContent, exportFilename, exportResponseHeaders, filterExportDataset, type ExportDataset } from "@/lib/export";
import type { ExpenseWithDetails } from "@/types/expense";

function expense(overrides: Partial<ExpenseWithDetails> = {}): ExpenseWithDetails {
  return { id: "e1", user_id: null, merchant: "REWE, Mitte", expense_date: "2026-07-21", amount: 9, currency: "EUR", category: "食品雜貨", payment_method: "VISA", receipt_image_url: "https://signed.example/token", receipt_image_path: "receipts/e1.jpg", raw_receipt_text: null, ai_confidence: null, notes: "第一行\n第二行", source: "chatgpt_import", import_warnings: [], import_idempotency_key: "secret-key", creation_idempotency_key: "manual-secret", created_at: "2026-07-21T00:00:00Z", updated_at: "2026-07-21T00:00:00Z", expense_items: [{ id: "i1", expense_id: "e1", name_original: "JA! H-MILCH", name_normalized: "牛奶", english_name: "Milk", brand: "JA!", product_group: "乳製品", quantity: 1, amount: 10, category: "食品雜貨", confidence: .98, unit: "L", unit_quantity: 1, notes: null, created_at: "", updated_at: "" }], expense_adjustments: [{ id: "a1", expense_id: "e1", name: "Coupon", amount: -1, category: "食品雜貨", created_at: "", updated_at: "" }], ...overrides };
}
const aliases = [{ id: "p1", alias: "H-MILCH", alias_normalized: "h-milch", normalized_name: "牛奶", product_group: "乳製品", category: "食品雜貨" as const, brand: "JA!", created_at: "", updated_at: "" }];
const dataset: ExportDataset = { expenses: [expense(), expense({ id: "e2", merchant: "Cafe", expense_date: "2026-01-03", amount: 4.5, currency: "USD", category: "餐飲", source: "manual", expense_items: [], expense_adjustments: [], receipt_image_path: null })], aliases };

describe("export center", () => {
  it("escapes commas, quotes and newlines in expense CSV", () => { const value = buildExpensesCsv(dataset); expect(value).toContain('"REWE, Mitte"'); expect(value).toContain('"第一行\n第二行"'); });
  it("exports Chinese CSV text", () => expect(buildExpensesCsv(dataset)).toContain("食品雜貨"));
  it("starts CSV with a UTF-8 BOM", () => expect(buildExpensesCsv(dataset).charCodeAt(0)).toBe(0xfeff));
  it("formats expense amounts to two decimals", () => expect(buildExpensesCsv(dataset)).toContain(",9.00,EUR,"));
  it("includes items and adjustments in item CSV", () => { const value = buildItemsCsv(dataset); expect(value).toContain(",item,"); expect(value).toContain(",adjustment,"); });
  it("keeps negative adjustments", () => expect(buildItemsCsv(dataset)).toContain(",-1.00,"));
  it("preserves full JSON relationships", () => expect(buildFullBackup(dataset, {}).expenses[0]).toMatchObject({ id: "e1", items: [{ english_name: "Milk" }], adjustments: [{ amount: -1 }] }));
  it("includes manual expenses in the ChatGPT bundle", () => expect(buildChatGPTBundle(dataset, {}).purchases.some((purchase) => purchase.source === "manual")).toBe(true));
  it("keeps manual items empty in both JSON exports without a placeholder", () => { expect(buildChatGPTBundle(dataset, {}).purchases.find((purchase) => purchase.source === "manual")?.items).toEqual([]); expect(buildFullBackup(dataset, {}).expenses.find((value) => value.source === "manual")?.items).toEqual([]); });
  it("uses N/A only for an explicitly created incomplete item", () => { const manual = expense({ source: "manual", amount: 0.5, expense_items: [{ ...expense().expense_items[0], name_original: null, name_normalized: null, english_name: null, brand: "", product_group: null, amount: 0.5 }] , expense_adjustments: [] }); expect(buildChatGPTBundle({ expenses: [manual], aliases: [] }, {}).purchases[0].items[0]).toMatchObject({ name_original: "N/A", name_normalized: "N/A", english_name: "N/A", brand: "N/A", product_group: "其他", amount: 0.5 }); });
  it("reconciles a matching itemized expense using cents", () => expect(buildChatGPTBundle({ expenses: [expense()], aliases: [] }, {}).purchases[0].reconciliation).toEqual({ item_total: 10, adjustment_total: -1, calculated_detail_total: 9, expense_total: 9, difference: 0, matches: true }));
  it("flags a mismatching expense and adds a purchase warning", () => { const purchase = buildChatGPTBundle({ expenses: [expense({ amount: 8.98 })], aliases: [] }, {}).purchases[0]; expect(purchase.reconciliation).toMatchObject({ calculated_detail_total: 9, expense_total: 8.98, difference: 0.02, matches: false }); expect(purchase.warnings.some((warning) => warning.includes("相差"))).toBe(true); });
  it("handles positive and negative adjustments in reconciliation", () => { const value = expense({ amount: 9, expense_items: [{ ...expense().expense_items[0], amount: 8 }], expense_adjustments: [{ ...expense().expense_adjustments[0], id: "positive", name: "Pfand", amount: 2 }, { ...expense().expense_adjustments[0], id: "negative", name: "Coupon", amount: -1 }] }); expect(buildChatGPTBundle({ expenses: [value], aliases: [] }, {}).purchases[0].reconciliation).toMatchObject({ item_total: 8, adjustment_total: 1, calculated_detail_total: 9, difference: 0, matches: true }); });
  it("reports reconciled and unreconciled counts without double counting totals", () => { const bundle = buildChatGPTBundle(dataset, {}); expect(bundle.summary).toMatchObject({ expense_count: 2, reconciled_expense_count: 1, unreconciled_expense_count: 1, total_by_currency: { EUR: 9, USD: 4.5 } }); expect(bundle.purchases[0].reconciliation.calculated_detail_total).toBe(9); });
  it("excludes sensitive and technical fields from both JSON formats", () => { const value = JSON.stringify([buildFullBackup(dataset, {}), buildChatGPTBundle(dataset, {})]); expect(value).not.toContain("secret-key"); expect(value).not.toContain("manual-secret"); expect(value).not.toContain("signed.example"); expect(value).not.toContain("receipt_image_url"); });
  it("keeps multi-currency totals separate", () => expect(buildChatGPTBundle(dataset, {}).summary.total_by_currency).toEqual({ EUR: 9, USD: 4.5 }));
  it("filters by inclusive date range", () => expect(filterExportDataset(dataset, { start: "2026-07-01", end: "2026-07-31" }).expenses).toHaveLength(1));
  it("filters merchant case-insensitively", () => expect(filterExportDataset(dataset, { merchant: "rewe" }).expenses).toHaveLength(1));
  it("filters expense or item category", () => expect(filterExportDataset(dataset, { category: "食品雜貨" }).expenses).toHaveLength(1));
  it("filters product group", () => expect(filterExportDataset(dataset, { product_group: "乳製" }).expenses).toHaveLength(1));
  it("filters brand", () => expect(filterExportDataset(dataset, { brand: "ja!" }).expenses).toHaveLength(1));
  it("filters source", () => expect(filterExportDataset(dataset, { source: "manual" }).expenses.map((value) => value.id)).toEqual(["e2"]));
  it("exports valid empty datasets", () => expect(() => JSON.parse(exportContent("full-json", { expenses: [], aliases: [] }, {}).body)).not.toThrow());
  it("normalizes missing legacy item fields without mutating input", () => { const legacy = expense({ expense_items: [{ ...expense().expense_items[0], english_name: null, brand: "", product_group: null, unit: null, unit_quantity: null, quantity: 1 }] }); const value = buildFullBackup({ expenses: [legacy], aliases: [] }, {}).expenses[0].items[0]; expect(value).toMatchObject({ english_name: "N/A", brand: "N/A", product_group: "其他", unit: "N/A", unit_quantity: 1 }); expect(legacy.expense_items[0].english_name).toBeNull(); });
  it("handles a large export", () => expect(buildExpensesCsv({ expenses: Array.from({ length: 5000 }, (_, index) => expense({ id: `e${index}` })), aliases: [] }).split("\r\n")).toHaveLength(5002));
  it("sets CSV and JSON Content-Type", () => { expect(exportResponseHeaders("expenses-csv", {})["Content-Type"]).toBe("text/csv; charset=utf-8"); expect(exportResponseHeaders("full-json", {})["Content-Type"]).toBe("application/json; charset=utf-8"); });
  it("sets attachment Content-Disposition", () => expect(exportResponseHeaders("full-json", {})["Content-Disposition"]).toContain("attachment; filename="));
  it("uses a stable date-range filename", () => expect(exportFilename("items-csv", { start: "2026-01-01", end: "2026-06-30" }, "2026-07-26")).toBe("receipt-tracker_items-csv_2026-01-01_to_2026-06-30_2026-07-26.csv"));
  it("uses the centralized export version", () => { expect(EXPORT_VERSION).toBe("1.0"); expect(buildChatGPTBundle(dataset, {}).export_version).toBe(EXPORT_VERSION); });
});
